--------------------------------------------------------
--  DDL for Table LOCK_JETON_MAITRE
--------------------------------------------------------

CREATE TABLE "LOCK_JETON_MAITRE" 
   (	"ID" VARCHAR2(36 BYTE), 
   	"ID_JETON_MAITRE" VARCHAR2(36 BYTE),
	"ID_PROPRIETAIRE" NVARCHAR2(2000), 
	"TYPE_WEBSERVICE" NVARCHAR2(2000), 
	"NUMERO_JETON" NUMBER(19,0)
   ) ;   
   
  CREATE UNIQUE INDEX "LOCK_JETON_MAITRE_PK" ON "LOCK_JETON_MAITRE" ("ID");
  
  ALTER TABLE "LOCK_JETON_MAITRE" ADD CONSTRAINT "LOCK_JETON_MAITRE_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "LOCK_JETON_MAITRE" MODIFY ("ID" NOT NULL ENABLE);
  
  ALTER TABLE "LOCK_JETON_MAITRE" ADD CONSTRAINT "LJM_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
	  
  ALTER TABLE "LOCK_JETON_MAITRE" ADD CONSTRAINT "LJM_ID_JETON_MAITRE_FK" FOREIGN KEY ("ID_JETON_MAITRE")
	  REFERENCES "JETON_MAITRE" ("ID") ON DELETE CASCADE ENABLE;
	  
commit; 