package fr.dila.st.ui.enums;

public enum STActionEnum implements ActionEnum {
    ADD_FAVORI_CONSULTATION,
    ADD_USER_FAVORI_RECHERCHE,
    ADMIN_BATCH,
    ADMIN_BATCH_SAVE_NOTIFICATION,
    ADMIN_RESEARCH_DELETE_USER,
    ADMIN_RESEARCH_SEND_MAIL,
    ADMIN_USER_ACCES,
    ADMIN_USER_EDIT_PASSWORD_CHANGE,
    ADMIN_USER_NEW_USER,
    ADMIN_USER_RECHERCHE,
    COPY_NODE,
    CREATE_ENTITE,
    CREATE_GOUVERNEMENT,
    CREATE_POSTE,
    CREATE_POSTE_WS,
    CREATE_UNITE_STRUCTURELLE,
    DISABLE_MINISTERE,
    DISABLE_NODE,
    ENABLE_MINISTERE,
    ENABLE_NODE,
    MODIFY_ENTITE,
    MODIFY_GOUVERNEMENT,
    MODIFY_POSTE,
    MODIFY_POSTE_WS,
    MODIFY_UNITE_STRUCTURELLE,
    PASTE_NODE_WITHOUT_USER,
    PASTE_NODE_WITH_USERS,
    REMOVE_MINISTERE,
    REMOVE_NODE,
    USER_EDIT_PASSWORD_CHANGE;

    @Override
    public String getName() {
        return name();
    }
}
