DELETE FROM VOC_TYPE_PJ;
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TEXTE',0,10000000,'Texte(s)');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('EXPOSE_DES_MOTIFS',0,10000000,'Exposé des motifs');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('ETUDE_IMPACT',0,10000000,'Étude d''impact');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('DECRET_PRESENTATION',0,10000000,'Décret de présentation');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_PM',0,10000000,'Lettre Premier Ministre');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TRAITE',0,10000000,'Traité');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('ACCORD_INTERNATIONAL',0,10000000,'Accord international');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('AUTRE',0,10000000,'Autre(s)');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('ANNEXE',0,10000000,'Annexe(s)');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('AVIS',0,10000000,'Avis');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('COHERENT',0,10000000,'Cohérent');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('COPIES_3_LETTRES_TRANSMISSION',0,10000000,'Copies 3 lettres transmission Vélins Petite loi (Congrès)');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('DECRET_PRESIDENT_REPUBLIQUE',0,10000000,'Décret du Président de la République');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE',0,10000000,'Lettre');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_CONJOINTE_PRESIDENTS',0,10000000,'Lettre conjointe des Présidents');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_SAISINE_CC',0,10000000,'Lettre de saisine du Conseil constitutionnel');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_PM_VERS_AN',0,10000000,'Lettre Premier Ministre à l''Assemblée Nationale');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_PM_VERS_SENAT',0,10000000,'Lettre Premier Ministre au Sénat');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LETTRE_TRANSMISSION',0,10000000,'Lettre Transmission');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('LISTE_ANNEXES',0,10000000,'Liste des annexes');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('PETITE_LOI',0,10000000,'Petite loi');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('RAPPORT',0,10000000,'Rapport');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TEXTE_ADOPTE',0,10000000,'Texte adopté');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TEXTE_MOTION',0,10000000,'Texte de la motion');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TEXTE_TRANSMIS',0,10000000,'Texte transmis');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('TRAVAUX_PREPARATOIRES',0,10000000,'Travaux préparatoires');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('CURRICULUM_VITAE',0,10000000,'Curriculum vitae');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('AMPLIATION_DECRET',0,10000000,'Ampliation Décret Président de la République');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('ECHEANCIER',0,10000000,'Echéancier');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('INSERTION_JOLD',0,10000000,'INSERTions au JO-LD');
INSERT INTO VOC_TYPE_PJ ("id","obsolete","ordering","label") values ('AMPLIATION_DECRET_PRESIDENT_REPUBLIQUE',0,10000000,'Ampliation Décret Président de la République');
commit;