--supprimer le niveau de lecture numero pour les niveaux autre que AN et SENAT
UPDATE VERSION 
SET NIVEAULECTURENUMERO = NULL
WHERE NIVEAULECTURE IN ('CMP', 'NOUVELLE_LECTURE_AN', 'NOUVELLE_LECTURE_SENAT', 'LECTURE_DEFINITIVE', 'CONGRES');
COMMIT;