ALTER TABLE "CASE_LINK" ADD "CASEDOCUMENTIDOLD" VARCHAR2(2000 CHAR);
UPDATE  "CASE_LINK" SET "CASEDOCUMENTIDOLD" = "CASEDOCUMENTID";
ALTER TABLE "CASE_LINK" DROP COLUMN "CASEDOCUMENTID" ;
ALTER TABLE "CASE_LINK" ADD "CASEDOCUMENTID" VARCHAR2(36 BYTE);
UPDATE  "CASE_LINK" SET "CASEDOCUMENTID" = "CASEDOCUMENTIDOLD";
ALTER TABLE "CASE_LINK" DROP COLUMN "CASEDOCUMENTIDOLD" ;

ALTER TABLE "CASE_LINK" ADD "ETATMESSAGEOLD" VARCHAR2(2000 CHAR);
UPDATE  "CASE_LINK" SET "ETATMESSAGEOLD" = "ETATMESSAGE";
ALTER TABLE "CASE_LINK" DROP COLUMN "ETATMESSAGE" ;
ALTER TABLE "CASE_LINK" ADD "ETATMESSAGE" VARCHAR2(50 CHAR);
UPDATE  "CASE_LINK" SET "ETATMESSAGE" = "ETATMESSAGEOLD";
ALTER TABLE "CASE_LINK" DROP COLUMN "ETATMESSAGEOLD" ;

CREATE UNIQUE INDEX "LIFECYCLESTATE_IDX" ON "MISC" ("ID", "LIFECYCLESTATE");
CREATE UNIQUE INDEX "MES_ETATMESSAGE_IDX" ON "CASE_LINK" ("ID", "ETATMESSAGE");
CREATE UNIQUE INDEX "MES_DATETRAITEMENT_IDX" ON "CASE_LINK" ("ID", "DATETRAITEMENT");

COMMIT;