CREATE TABLE "INSTITUTION"
(	"ID_ORGANIGRAMME" NVARCHAR2(255) NOT NULL,
		"DATE_FIN" TIMESTAMP(6),
		"DATE_DEBUT" TIMESTAMP(6),
		"DATE_VERROU" TIMESTAMP(6),
		"LABEL" NVARCHAR2(255),
		"DELETED" NUMBER(1,0),
		"UTILISATEUR_VERROU" NVARCHAR2(255),
		"FUNCTION_READ" NVARCHAR2(255)
   ) ;
   CREATE UNIQUE INDEX "ID_INSTITUTION_PK" ON "INSTITUTION" ("ID_ORGANIGRAMME") TABLESPACE INDX;
	ALTER TABLE "INSTITUTION" ADD CONSTRAINT "INSTITUTION_PK" PRIMARY KEY ("ID_ORGANIGRAMME") ENABLE;

CREATE TABLE "ENTITE"
(	"ID_ORGANIGRAMME" NVARCHAR2(255) NOT NULL,
		"DATE_FIN" TIMESTAMP(6),
		"DATE_DEBUT" TIMESTAMP(6),
		"DATE_VERROU" TIMESTAMP(6),
		"LABEL" NVARCHAR2(255),
		"DELETED" NUMBER(1,0),
		"UTILISATEUR_VERROU" NVARCHAR2(255),
		"ID_PARENT_GOUV" NVARCHAR2(255),
		"EDITION" NVARCHAR2(255),
		"FORMULE" NVARCHAR2(255),
		"CIVILITE_MINISTRE" NVARCHAR2(255),
		"NOM_MINISTRE" NVARCHAR2(255),
		"PRENOM_MINISTRE" NVARCHAR2(255),
		"ORDRE" NUMBER(19,0),
		"FUNCTION_READ" NVARCHAR2(255),
		"NOR_MINISTERE" VARCHAR2(3500),
		"SUIVI_ACTIVITE_NORMATIVE" NUMBER(1,0));
   CREATE UNIQUE INDEX "ID_ENTITE_PK" ON "ENTITE" ("ID_ORGANIGRAMME") TABLESPACE INDX;
	ALTER TABLE "ENTITE" ADD CONSTRAINT "ENTITE_PK" PRIMARY KEY ("ID_ORGANIGRAMME") ENABLE;
	
CREATE TABLE "UNITE_STRUCTURELLE"
(	"ID_ORGANIGRAMME" NVARCHAR2(255) NOT NULL,
		"DATE_FIN" TIMESTAMP(6),
		"DATE_DEBUT" TIMESTAMP(6),
		"DATE_VERROU" TIMESTAMP(6),
		"LABEL" NVARCHAR2(255),
		"DELETED" NUMBER(1,0),
		"UTILISATEUR_VERROU" NVARCHAR2(255),
		"ID_PARENT_ENTITE" VARCHAR2(3500),
		"ID_PARENT_UNITE" VARCHAR2(3500),
		"ID_PARENT_INSTITUTION" VARCHAR2(3500),
		"TYPE" NVARCHAR2(255),
		"FUNCTION_READ" NVARCHAR2(255),
		"NOR_DIRECTION" VARCHAR2(3500)) ;
   CREATE UNIQUE INDEX "ID_UNITE_PK" ON "UNITE_STRUCTURELLE" ("ID_ORGANIGRAMME") TABLESPACE INDX;
	ALTER TABLE "UNITE_STRUCTURELLE" ADD CONSTRAINT "UNITE_PK" PRIMARY KEY ("ID_ORGANIGRAMME") ENABLE;

CREATE TABLE "POSTE"
(	"ID_ORGANIGRAMME" NVARCHAR2(255) NOT NULL,
		"DATE_FIN" TIMESTAMP(6),
		"DATE_DEBUT" TIMESTAMP(6),
		"DATE_VERROU" TIMESTAMP(6),
		"LABEL" NVARCHAR2(255),
		"DELETED" NUMBER(1,0),
		"UTILISATEUR_VERROU" NVARCHAR2(255),
		"ID_PARENT_ENTITE" VARCHAR2(3500),
		"ID_PARENT_UNITE" VARCHAR2(3500),
		"ID_PARENT_INSTITUTION" VARCHAR2(3500),
		"CHARGE_MISSION_SGG" NUMBER(1,0),
		"POSTE_BDC" NUMBER(1,0),
		"SUPERVISEUR_SGG" NUMBER(1,0),
		"CONSEILLER_PM" NUMBER(1,0),
		"POSTE_WS" NUMBER(1,0),
		"WS_URL" NVARCHAR2(500),
		"WS_LOGIN" NVARCHAR2(255),
		"WS_MDP" NVARCHAR2(255),
		"WS_CLE" NVARCHAR2(255),
		"MEMBRES" VARCHAR2(3500),
		"FUNCTION_READ" NVARCHAR2(255)) ;
   CREATE UNIQUE INDEX "ID_POSTE_PK" ON "POSTE" ("ID_ORGANIGRAMME") TABLESPACE INDX;
	ALTER TABLE "POSTE" ADD CONSTRAINT "POSTE_PK" PRIMARY KEY ("ID_ORGANIGRAMME") ENABLE;
commit;
