-- Création de la table pour l'affichage de la banniere en page d'accueil
CREATE TABLE "ETAT_APPLICATION"
(  	"ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION_RESTRICTION" NVARCHAR2(2000), 
	"RESTRICTION_ACCES" NUMBER(1,0), 
   	"AFFICHAGE" NUMBER(1,0),  
   	"MESSAGE" CLOB
   );  
ALTER TABLE "ETAT_APPLICATION" ADD CONSTRAINT "ETAT_APPLICATION_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ETAT_APPLICATION" ADD CONSTRAINT "ETAT_APPLICATION_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
commit;

