   CREATE TABLE "HISTORIQUE_MDP"
   ("ID" NUMBER(19,0) NOT NULL ENABLE,
	"LOGIN" VARCHAR2(255 CHAR),
	"DERNIER_MDP" VARCHAR2(255 CHAR),
	"DATE_ENREGISTREMENT" TIMESTAMP(6),
	 PRIMARY KEY ("ID")
   );
