delete from VOC_TYPE_LOI;
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_CONSTITUTIONNELLE',0,10000000,'Loi constitutionnelle');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_REFERENDAIRE',0,10000000,'Loi référendaire');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_ORGANIQUE',0,10000000,'Loi organique');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_FINANCE',0,10000000,'Loi de finances');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_FINANCE_RECTIFICATIVE',0,10000000,'Loi de finances rectificative');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_REGLEMENT',0,10000000,'Loi de règlement');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_FINANCEMENT_SECURITE_SOCIALE',0,10000000,'Loi de financement de la sécurité sociale');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('ART_53_CONST',0,10000000,'Loi autorisant la ratification ou l''approbation de traités ou accords internationaux');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_PROGRAMMATION',0,10000000,'Loi de programmation');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_ORIENTATION',0,10000000,'Loi d''orientation');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI',0,10000000,'Loi');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_CADRE',0,10000000,'Loi cadre');
insert into VOC_TYPE_LOI ("id","obsolete","ordering","label") values ('LOI_FINANCEMENT_SECURITE_SOCIALE_RECTIFICATIVE',0,10000000,'Loi de financement de la sécurité sociale rectificative');
commit;