-- FEV319
-- Ajouter la colonne nature dans la version et initialisation

ALTER TABLE "VERSION" ADD "NATURE" NVARCHAR2(2000);

ALTER TABLE "VERSION" ADD "VERSIONCOURANTE" NUMBER(1,0);

-- MAJ de la table "VERSION" champs "VERSIONCOURANTE"
-- Mise a true de la version majeur la plus grande de chaque evenement
UPDATE "VERSION" SET "VERSION"."VERSIONCOURANTE" = '1' 
WHERE "VERSION"."ID" in (
    SELECT VER."ID" FROM "VERSION" VER, ( 
        SELECT V."EVENEMENT", max(V."MAJORVERSION") as MAJ
        FROM "VERSION" V
        GROUP BY V."EVENEMENT" ) S
    WHERE VER."MAJORVERSION" = S."MAJ" AND VER."EVENEMENT" = S."EVENEMENT" and VER.MinorVERSION = 0);


-- MAJ de la table "VERSION" champs "NATURE" 
-- BROUILLON_COMPLETION / PUBLIE_COMPLETION
UPDATE "VERSION" V
SET V."NATURE" = 'COMPLETEE'
WHERE V."MODECREATION" = 'BROUILLON_COMPLETION' OR V."MODECREATION" = 'PUBLIE_COMPLETION';
  

-- MAJ de la table "VERSION" champs "NATURE" 
-- BROUILLON_RECTIFICATION
UPDATE "VERSION" V
SET V."NATURE" = 'RECTIFIEE'
WHERE V."MODECREATION" = 'BROUILLON_RECTIFICATION';

-- MAJ de la table "VERSION" champs "NATURE"
-- Modecreation = PUBLIE_DEMANDE_RECTIFICATION / PUBLIE_DELTA_DEMANDE_RECTIFICATION 
-- Lifecyclestate = 'init','brouillon', 'publie', 'brouillonAttenteValidation', 'attenteValidation', 'obsolete'
UPDATE "VERSION" V
SET V."NATURE" = 'RECTIFICATION_EN_COURS'
WHERE (V."MODECREATION" = 'PUBLIE_DEMANDE_RECTIFICATION' OR V."MODECREATION"= 'PUBLIE_DELTA_DEMANDE_RECTIFICATION') AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" IN ('init','brouillon', 'publie', 'brouillonAttenteValidation', 'attenteValidation', 'obsolete')
    );

-- MAJ de la table "VERSION" champs "NATURE" 
-- Modecreation = PUBLIE_DEMANDE_RECTIFICATION / PUBLIE_DELTA_DEMANDE_RECTIFICATION 
-- Lifecyclestate = 'rejete'
UPDATE "VERSION" V
SET V."NATURE" = 'RECTIFICATION_REJETEE'
WHERE (V."MODECREATION" = 'PUBLIE_DEMANDE_RECTIFICATION' OR V."MODECREATION"= 'PUBLIE_DELTA_DEMANDE_RECTIFICATION') AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" = 'rejete'
    );  
    
-- MAJ de la table "VERSION" champs "NATURE" 
-- Modecreation = PUBLIE_DEMANDE_RECTIFICATION / PUBLIE_DELTA_DEMANDE_RECTIFICATION 
-- Lifecyclestate = 'abandonne'
UPDATE "VERSION" V
SET V."NATURE" = 'RECTIFICATION_ABANDONNEE'
WHERE (V."MODECREATION" = 'PUBLIE_DEMANDE_RECTIFICATION' OR V."MODECREATION"= 'PUBLIE_DELTA_DEMANDE_RECTIFICATION') AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" = 'abandonne'
    );
    
-- MAJ de la table "VERSION" champs "NATURE" 
-- PUBLIE_VALIDATION_RECTIFICATION / PUBLIE_RECTIFICATION
UPDATE "VERSION" V
SET V."NATURE" = 'RECTIFIEE'
WHERE V."MODECREATION" = 'PUBLIE_VALIDATION_RECTIFICATION' OR V."MODECREATION" = 'PUBLIE_RECTIFICATION';
    
    
-- MAJ de la table "VERSION" champs "NATURE"
-- Modecreation = PUBLIE_DEMANDE_RECTIFICATION / PUBLIE_DELTA_DEMANDE_RECTIFICATION 
-- Lifecyclestate = 'init','brouillon', 'publie', 'brouillonAttenteValidation', 'attenteValidation', 'obsolete'
UPDATE "VERSION" V
SET V."NATURE" = 'ANNULATION_EN_COURS'
WHERE V."MODECREATION" = 'PUBLIE_DEMANDE_ANNULATION' AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" IN ('init','brouillon', 'publie', 'brouillonAttenteValidation', 'attenteValidation', 'obsolete')
    );

-- MAJ de la table "VERSION" champs "NATURE" 
-- Modecreation = PUBLIE_DEMANDE_ANNULATION
-- Lifecyclestate = 'rejete'
UPDATE "VERSION" V
SET V."NATURE" = 'ANNULATION_REJETEE'
WHERE V."MODECREATION" = 'PUBLIE_DEMANDE_ANNULATION' AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" = 'rejete'
    );  
    
-- MAJ de la table "VERSION" champs "NATURE" 
-- Modecreation = PUBLIE_DEMANDE_RECTIFICATION / PUBLIE_DELTA_DEMANDE_RECTIFICATION 
-- Lifecyclestate = 'abandonne'
UPDATE "VERSION" V
SET V."NATURE" = 'ANNULATION_ABANDONNEE'
WHERE V."MODECREATION" = 'PUBLIE_DEMANDE_ANNULATION' AND
V."ID" IN
(   SELECT VER."ID"
    FROM "MISC" M, "VERSION" VER
    WHERE M."ID" = VER."ID" AND M."LIFECYCLESTATE" = 'abandonne'
    );
    

-- MAJ de la table "VERSION" champs "NATURE" 
-- PUBLIE_VALIDATION_ANNULATION / PUBLIE_ANNULATION
UPDATE "VERSION" V
SET V."NATURE" = 'ANNULEE'
WHERE V."MODECREATION" = 'PUBLIE_VALIDATION_ANNULATION' OR V."MODECREATION" = 'PUBLIE_ANNULATION';


COMMIT;