
-- FEV323
-- Ajouter la colonne bulletin blanc et des données manquantes pour la fiche dossier EVT 32 et 34

ALTER TABLE "VERSION" ADD "BULLETINBLANC" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "SENSAVIS" NVARCHAR2(2000);

ALTER TABLE "DOSSIER" ADD "BULLETINBLANC" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "VOTEPOUR" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "VOTECONTRE" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "SUFFRAGEEXPRIME" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "ABSTENTION" NUMBER(19,0);

ALTER TABLE "DOSSIER" ADD "DATEACTE" TIMESTAMP (6);

ALTER TABLE "DOSSIER" ADD "TYPEACTE" NVARCHAR2(2000);

ALTER TABLE "DOSSIER" ADD "ECHEANCE" NVARCHAR2(2000);

CREATE TABLE "DOS_COMMISSIONS"
(	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"POS" NUMBER(10,0),
	"ITEM" NVARCHAR2(2000),
	 CONSTRAINT "DOS_SENSAVIS_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
);

COMMIT;