  CREATE TABLE "VOC_DEC_PROC_ACC" 
   (	
    "id" NVARCHAR2(2000), 
	"obsolete" NUMBER(19,0) DEFAULT 0, 
	"ordering" NUMBER(19,0) DEFAULT 10000000, 
	"label" NVARCHAR2(2000)
   ) ;

COMMIT;

INSERT INTO VOC_DEC_PROC_ACC ("id","obsolete","ordering","label") values ('ACCEPTATION',0,10000000,'Acceptation');
INSERT INTO VOC_DEC_PROC_ACC ("id","obsolete","ordering","label") values ('REFUS',0,10000000,'Refus');
commit;

ALTER TABLE "VERSION" ADD "DATEREFUSASSEMBLEE1" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "DATECONFERENCEASSEMBLEE2" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "DECISIONPROCACC" NVARCHAR2(2000);
ALTER TABLE "VERSION" ADD "DATEREFUSENGAGEMENTPROCEDURE" TIMESTAMP(6);

ALTER TABLE "DOSSIER" ADD "DATEREFUSASSEMBLEE1" TIMESTAMP(6);
ALTER TABLE "DOSSIER" ADD "DATECONFERENCEASSEMBLEE2" TIMESTAMP(6);
ALTER TABLE "DOSSIER" ADD "DECISIONPROCACC" NVARCHAR2(2000);
ALTER TABLE "DOSSIER" ADD "DATEREFUSENGAGEMENTPROCEDURE" TIMESTAMP(6);

commit;
