ALTER TABLE "VERSION" ADD "DATEDECLARATION" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "DEMANDEVOTE" NUMBER(1,0);
ALTER TABLE "VERSION" ADD "DATEPRESENTATION" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "DATEAUDITION" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "FONCTION" NVARCHAR2(2000);
ALTER TABLE "VERSION" ADD "PERSONNE" NVARCHAR2(2000);
ALTER TABLE "VERSION" ADD "DATELETTREPM" TIMESTAMP(6);
ALTER TABLE "VERSION" ADD "ORGANISME" NVARCHAR2(2000);
CREATE TABLE "VER_GROUPEPARLEMENTAIRE"
(
	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"POS" NUMBER(10,0),
	"ITEM" NVARCHAR2(2000),
	CONSTRAINT "HIER_VER_GP_PARL_FK" FOREIGN KEY ("ID")	                 
	REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
);
