CREATE TABLE "VOC_RUBRIQUES" 
   (	"id" NVARCHAR2(2000), 
	"obsolete" NUMBER(19,0) DEFAULT 0, 
	"ordering" NUMBER(19,0) DEFAULT 10000000, 
	"label" NVARCHAR2(2000),
	"forAssNat" NUMBER(1,0) DEFAULT 0 NOT NULL,
	"forSenat" NUMBER(1,0) DEFAULT 0 NOT NULL,
	"forCMP" NUMBER(1,0) DEFAULT 0 NOT NULL,
	"forOffDel" NUMBER(1,0) DEFAULT 0 NOT NULL,
	"forGroupeTravail" NUMBER(1,0) DEFAULT 0 NOT NULL,
	"forCongres" NUMBER(1,0) DEFAULT 0 NOT NULL
   );

