CREATE TABLE "PARAMETRAGE_WS_EPG"(
    "ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "NORDIRECTIONAN" NVARCHAR2(255),
    "NORDIRECTIONSENAT" NVARCHAR2(255),
    "NORENTITE"NVARCHAR2(255),
    "NORDIRECTIONAUTRES"NVARCHAR2(255)
);

