INSERT INTO "INSTITUTION"(ID_ORGANIGRAMME, LABEL, DELETED) VALUES('CMP', 'Commission mixte paritaire', 0);
INSERT INTO "INSTITUTION"(ID_ORGANIGRAMME, LABEL, DELETED) VALUES('OFFICES_DELEGATIONS', 'Offices et délégations', 0);
INSERT INTO "INSTITUTION"(ID_ORGANIGRAMME, LABEL, DELETED) VALUES('GRP_AN_SENAT', 'Groupes de travail Assemblée nationale - Sénat', 0);
INSERT INTO "INSTITUTION"(ID_ORGANIGRAMME, LABEL, DELETED) VALUES('CONGRES_PARLEMENT', 'Congrès', 0);

COMMIT;
