package fr.dila.ss.ui.enums;

import fr.dila.st.ui.enums.ActionEnum;

public enum SSActionEnum implements ActionEnum {
    ADD_BRANCH,
    ADD_FDR_FAVORI_RECHERCHE,
    ADD_STEP_AFTER,
    ADD_STEP_AFTER_BRANCH,
    ADD_STEP_BEFORE,
    ADD_STEP_BEFORE_BRANCH,
    ADMIN_JOURNAL_TECHNIQUE,
    ADMIN_MENU_MODELE_RECHERCHE,
    ADMIN_MIGRATION_HISTORIQUE,
    ADMIN_MIGRATION_MIGRATIONS,
    ADMIN_MODELES_FDR_FONCTIONNEL,
    ADMIN_MODELES_FDR_MINISTERIEL,
    ADMIN_PARAM,
    ADMIN_PARAM_TECHNIQUE,
    ADMIN_PROFIL_CREATE,
    ADMIN_PROFIL_DELETE,
    ADMIN_PROFIL_EDIT,
    ADMIN_USER_ACTUALITES,
    ADMIN_USER_PROFILS,
    ADMIN_USER_SUPERVISION,
    CONFIRM_IMPORT_GOUVERNEMENT,
    COPY_STEP_FDR,
    COPY_STEP_MODELE,
    CREATE_NEWS,
    DOSSIER_SUBSTITUER_FDR,
    DOSSIER_SUBSTITUER_FDR_VALIDER,
    EXPORT_GOUVERNEMENT,
    EXPORT_ZIP_STATS,
    FOND_DOSSIER_EXPORT,
    IMPORT_GOUVERNEMENT,
    MODELE_ACTION_CREER_MODELE,
    MOVE_STEP_DOWN,
    MOVE_STEP_UP,
    PASTE_STEP_AFTER,
    PASTE_STEP_BEFORE,
    RECHERCHE_ADMIN_ACTION_EXPORT,
    RECHERCHE_MODELE_EXPORT,
    REMOVE_SERIAL_BRANCH,
    REMOVE_STEP,
    REMOVE_STEP_BRANCH,
    REMOVE_ZIP_STATS,
    SUPERVISION_ACTION_LIST,
    SUPERVISION_ACTION_MAIL,
    TAB_DOSSIER_JOURNAL,
    UPDATE_STEP,
    UPDATE_STEP_MODELE;

    @Override
    public String getName() {
        return name();
    }
}
