package fr.dila.ss.ui.enums;

import fr.dila.st.ui.enums.ActionCategory;

public enum SSActionCategory implements ActionCategory {
    ADMIN_EDIT_PARAMETER,
    ADMIN_MENU_MODELE_MODELES,
    DOSSIER_TAB_ACTIONS,
    DOSSIER_TOPBAR_ACTIONS_DIVERS,
    DOSSIER_TOPBAR_ACTIONS_FDR,
    DOSSIER_TOPBAR_ACTIONS_GENERAL,
    DOSSIER_TOPBAR_ACTIONS_LOCKS,
    DOSSIER_TOPBAR_ACTIONS_NOTE,
    DOSSIER_TOPBAR_ACTIONS_PRINT,
    DOSSIER_TOPBAR_ACTIONS_RENVOI,
    FAVORIS_RECHERCHE_FDR_ACTIONS,
    FDR_ACTIONS,
    FDR_STEP_ACTIONS,
    FOND_DOSSIER_FILE_ACTIONS,
    FOND_DOSSIER_FOLDER_ACTIONS,
    MANAGE_NEWS_REMOVAL,
    MODELE_FDR_ACTIONS,
    MODELE_FDR_MASS_ACTIONS,
    MODELE_FDR_STEP_ACTIONS,
    MODELE_FDR_SUPPR_MASSE_ACTIONS,
    MODELE_FICHE_LEFT_ACTIONS,
    MODELE_FICHE_RIGHT_ACTIONS,
    MODELE_TAB_ACTION,
    /** Catégorie des actions générales "tertiaires" sur l'organigramme */
    ORGANIGRAMME_BASE_ACTIONS,
    /** Catégorie des actions primaires et secondaires sur l'organigramme */
    ORGANIGRAMME_MAIN_ACTIONS,
    PROFIL_CREATION_ACTIONS,
    PROFIL_MODIFICATION_ACTIONS,
    ROUTE_STEP_NOTE_ACTIONS,
    STAT_ACTIONS_DOWNLOAD,
    STEP_ACTIONS_LIST,
    STEP_FOLDER_PARALLEL_ACTIONS_LIST,
    STEP_FOLDER_SERIAL_ACTIONS_LIST,
    SUBSTITUTION_ACTIONS_LEFT,
    SUBSTITUTION_ACTIONS_RIGHT,
    SUPERVISION_ACTION_LIST,
    SUPERVISION_ACTION_MAIL,
    SUPERVISION_ACTION_PRINT,
    SUPERVISION_ACTION_PRINT_NOT_CONNECTED;

    @Override
    public String getName() {
        return name();
    }
}
