-- Cosignataire n'est plus multivalué
DROP INDEX DOS_COSIGNATAIRE_ID_IDX;
DROP INDEX VER_COSIGNATAIRE_ID_IDX;

DROP TABLE DOS_COSIGNATAIRE;
DROP TABLE VER_COSIGNATAIRE;

ALTER TABLE DOSSIER ADD COSIGNATAIRE NVARCHAR2(2000);
ALTER TABLE VERSION ADD COSIGNATAIRE NVARCHAR2(2000);

commit;