CREATE TABLE "VER_DATELIST"
   (    "ID" VARCHAR2(36) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" TIMESTAMP (6),
     CONSTRAINT "VER_DATELIST_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
      REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );
   
CREATE TABLE "DOS_DATELIST"
   (    "ID" VARCHAR2(36) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" TIMESTAMP (6),
     CONSTRAINT "DOS_DATELIST_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
      REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );
   
COMMIT;