ALTER TABLE "DOSSIER" ADD "URLDOSSIERAN" NVARCHAR2(2000);
ALTER TABLE "DOSSIER" ADD "URLDOSSIERSENAT" NVARCHAR2(2000);
ALTER TABLE "DOSSIER" DROP column "URLDOSSIER";

ALTER TABLE "VERSION" ADD "URLDOSSIERAN" NVARCHAR2(2000);
ALTER TABLE "VERSION" ADD "URLDOSSIERSENAT" NVARCHAR2(2000);
ALTER TABLE "VERSION" DROP column "URLDOSSIER";

COMMIT;