version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.13
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
      KAFKA_OFFSETS_RETENTION_MINUTES: 20160
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 4
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
