-- Ajout de la table pour le suivi des batchs
CREATE TABLE "BATCH_LOG" 
   (	"ID_LOG" NUMBER(19,0) NOT NULL,
		"END_TIME" TIMESTAMP(6),
		"ERROR_COUNT" NUMBER(19,0) NOT NULL,
		"NAME" NVARCHAR2(255) NOT NULL,
		"PARENT_ID" NUMBER(19,0),
		"SERVER" NVARCHAR2(255) NOT NULL,
		"START_TIME" TIMESTAMP(6) NOT NULL,
		"TOMCAT" NUMBER(19,0) NOT NULL,
		"TYPE" NVARCHAR2(255) NOT NULL
   ) ;
   
	CREATE UNIQUE INDEX "BATCH_LOG_PK" ON "BATCH_LOG" ("ID_LOG");
	ALTER TABLE "BATCH_LOG" ADD CONSTRAINT "BATCH_LOG_PK" PRIMARY KEY ("ID_LOG") ENABLE;
   
CREATE TABLE "BATCH_RESULT" 
   (	"ID_RESULT" NUMBER(19,0) NOT NULL,
		"ID_LOG" NUMBER(19,0) NOT NULL,
		"EXECUTION_RESULT" NUMBER(19,0),
		"EXECUTION_TIME" NUMBER(19,0) NOT NULL,
		"TEXT" NVARCHAR2(2000) NOT NULL
   ) ;
   
	CREATE UNIQUE INDEX "BATCH_RESULT_PK" ON "BATCH_RESULT" ("ID_RESULT");
	ALTER TABLE "BATCH_RESULT" ADD CONSTRAINT "BATCH_RESULT_PK" PRIMARY KEY ("ID_RESULT") ENABLE;
	
	ALTER TABLE "BATCH_RESULT" ADD CONSTRAINT "BR_ID_BATCH_LOG_FK" FOREIGN KEY ("ID_LOG")
	  REFERENCES "BATCH_LOG" ("ID_LOG") ON DELETE CASCADE ENABLE;
   
-- Ajouts pour les notifications
CREATE TABLE "NOTIFICATIONS_SUIVI_BATCHS"
   (	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"ETAT_NOTIFICATION" NUMBER(1,0),
	 CONSTRAINT "NOTIFICATIONS_SUIVI_BATCHS_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "NOTI_B002CA82_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );
   
CREATE TABLE "NSB_RECEIVERMAILLIST"
   (	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"POS" NUMBER(10,0),
	"ITEM" NVARCHAR2(2000),
	 CONSTRAINT "NSB__021DEF94_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );
	  
commit;