ALTER TABLE "CASE_LINK" ADD "IDDOSSIER" VARCHAR2(2000 CHAR);

ALTER TABLE "CASE_LINK" ADD "IDEVENEMENT" VARCHAR2(2000 CHAR);

ALTER TABLE "EVENEMENT" ADD "IDEVENEMENT" VARCHAR2(2000 CHAR);

ALTER TABLE "VERSION" ADD "COMMENTAIRE" VARCHAR2(2000 CHAR);

ALTER TABLE "DOSSIER" ADD "IDDOSSIER" VARCHAR2(2000 CHAR);

commit;

UPDATE "CASE_LINK" c set c."IDEVENEMENT" = (SELECT d."TITLE" FROM "DUBLINCORE" d where c.id = d.id );

UPDATE "EVENEMENT" c set c."IDEVENEMENT" = (SELECT d."TITLE" FROM "DUBLINCORE" d where c.id = d.id );

UPDATE "VERSION" c set c."COMMENTAIRE" = (SELECT d."DESCRIPTION" FROM "DUBLINCORE" d where c.id = d.id );

UPDATE "CASE_LINK" c set c."IDDOSSIER" = (SELECT e."DOSSIER" FROM "EVENEMENT" e where e.id = c.casedocumentid );

UPDATE "DOSSIER" c set c."IDDOSSIER" = (SELECT d."TITLE" FROM "DUBLINCORE" d where c.id = d.id );

commit;

ALTER TABLE "CASE_LINK" ADD "ACTIVEVERSIONIDOLD" VARCHAR2(2000 CHAR);
UPDATE  "CASE_LINK" SET "ACTIVEVERSIONIDOLD" = "ACTIVEVERSIONID";
ALTER TABLE "CASE_LINK" DROP COLUMN "ACTIVEVERSIONID" ;
ALTER TABLE "CASE_LINK" ADD "ACTIVEVERSIONID" VARCHAR2(36 BYTE);
UPDATE  "CASE_LINK" SET "ACTIVEVERSIONID" = "ACTIVEVERSIONIDOLD";
ALTER TABLE "CASE_LINK" DROP COLUMN "ACTIVEVERSIONIDOLD" ;

commit;