CREATE UNIQUE INDEX "EVT_DOSSIER_IDX" ON "EVENEMENT" ("ID", "DOSSIER");
CREATE UNIQUE INDEX "EVT_IDEVENEMENT_IDX" ON "EVENEMENT" ("ID", "IDEVENEMENT");
CREATE UNIQUE INDEX "EVT_EMETTEUR_IDX" ON "EVENEMENT" ("ID", "EMETTEUR");
CREATE UNIQUE INDEX "EVT_DESTINATAIRE_IDX" ON "EVENEMENT" ("ID", "DESTINATAIRE");

CREATE UNIQUE INDEX "MES_ACTIVEVERSIONID_IDX" ON "CASE_LINK" ("ID", "ACTIVEVERSIONID");
CREATE UNIQUE INDEX "MES_CASEDOCUMENTID_IDX" ON "CASE_LINK" ("ID", "CASEDOCUMENTID");

CREATE UNIQUE INDEX "VER_HORODATAGE_IDX" ON "VERSION" ("ID", "HORODATAGE");

CREATE UNIQUE INDEX "DOS_DOSSIER_IDX" ON "DOSSIER" ("ID", "IDDOSSIER");

commit;