INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('Browse');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('Classify');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('Read');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('ReadProperties');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('ReadRemove');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('ReadWrite');

INSERT INTO "ACLR_PERMISSION" ("PERMISSION") VALUES('Everything');

